### ISSUE TITLE
Support full-qualified path to schematic name

### ISSUE THREAD

**Issue by apryor6** [apryor6/flaskerize#21]
Currently, schematics are targeted by `<package_name>:<schematic_name>` syntax (other than the ones built-in to `flaskerize`, which may drop the leading `flaskerize:`, which requires the schematics be housed in a full Python package. A nice improvement would be to also support providing the fully-qualified path to the schematic. This will be quite simple to implement, as the functionality for loading an arbitrary python file, which is a little involved, is already present (the `<package_name>:<schematic_name>` syntax is parsed and `<package_name>` is inspected to identify its location, and from there it is all paths anyway). We would just need a relatively top-level check for a "path-like".

**Comment by mvellasco** [comment]
Hey @apryor6 , I saw that the other issue was pretty much done already. Can I give a hand on this one?

**Comment by apryor6** [comment]
Certainly — Open a PR and I’ll be happy to take a look. Know it advance that there will need to be tests on everything, but I’m happy to help with that. If you put together useful code, we’ll find a way to make it work.

Appreciate the enthusiasm!

**Comment by apryor6** [comment]
For this, there are two syntaxes that I think should be supported.

1) `fz generate full/path/to/schematics/schematic_name` 
2) `fz generate full/path/to/schematics:schematic_name`

**Comment by apryor6** [comment]
Implemented in #35
