### ISSUE TITLE
Respect existing static_folder

### ISSUE THREAD

**Issue by apryor6** [apryor6/flaskerize#3]
For target apps that have already specified `static_folder`, `flaskerize` should instead attach the site somewhere within so that the original Flask app is not broken

**Comment by mvellasco** [comment]
Hey @apryor6 hope you're well. I really liked the project, and I'd like to help out. Can I start working with this task?

**Comment by apryor6** [comment]
Hi there and welcome!

This issue was _mostly_ addressed in [e5f012](https://github.com/apryor6/flaskerize/commit/e5f012a3f79848aced320eea973a98575b99b596). Sloppy on my part not to reference this issue. I'll close it for now.

However, there is a much larger refactor coming in the next few weeks or so regarding how existing source code is modified. 

See [this issue](https://github.com/apryor6/flaskerize/issues/8) for further discussion
