### ISSUE TITLE
Create a docs site for flaskerize

### ISSUE THREAD

**Issue by martinpeck** [apryor6/flaskerize#34]
flaskerize would benefit from a quick start guide, and that guide should be part of a set of "official" documentation hosted on readthedocs.org. The creation of some basic docs will also allow other contributors to add/amend the docs over time.

The following structure should be created as a min:

- [x] Short welcome/introduction to flaskerize
- [x] Quick start guide: intro
- [x] Quick start guide: setup and installation
- [x] Quick start guide: creating the API
- [x] Quick start guide: adding an entity to the API

**Comment by martinpeck** [comment]
Draft pull request #33 tracks the work in progress against this issue.

**Comment by martinpeck** [comment]
I've tackled all of the above to some level or other, so I'm going to tick the boxes for those tasks.

**Comment by apryor6** [comment]
Closed by #33 and documentation is hosted on readthedocs [here](https://flaskerize.readthedocs.io/en/latest/)
